# Generated by Django 2.0.5 on 2018-06-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(default='upload/image/default.png', upload_to='upload/image/%Y/%m'),
        ),
        migrations.AddField(
            model_name='users',
            name='mobile',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(error_messages={'unique': '该电子邮箱已被占用'}, max_length=254, unique=True, verbose_name='电子邮箱'),
        ),
    ]
