# Generated by Django 2.0.5 on 2018-06-05 02:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('users', '0002_auto_20180604_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='医生描述')),
                ('name', models.CharField(max_length=50, verbose_name='医生名')),
                ('work_years', models.IntegerField(default=0, verbose_name='工作年限')),
                ('work_position', models.CharField(choices=[('zzys', '主治医师'), ('fzrys', '副主任医师'), ('zrys', '主任医师')], default='', max_length=5, verbose_name='医生职称')),
                ('points', models.CharField(max_length=300, verbose_name='擅长领域')),
                ('click_nums', models.PositiveIntegerField(default=0, verbose_name='点击数')),
                ('fav_nums', models.PositiveIntegerField(default=0, verbose_name='收藏数')),
                ('thumbsup_nums', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital', verbose_name='所属医院')),
            ],
            options={
                'verbose_name': '医生信息',
                'verbose_name_plural': '医生信息',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
