# Generated by Django 2.0.5 on 2018-06-05 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180605_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='work_position',
            new_name='title',
        ),
    ]
