# Generated by Django 2.0.5 on 2018-06-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180605_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='title',
            field=models.SmallIntegerField(choices=[(0, '主治医师'), (1, '副主任医师'), (2, '主任医师')], default=0, verbose_name='医生职称'),
        ),
    ]
