# Generated by Django 2.0.5 on 2018-06-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180605_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='real_name',
            field=models.CharField(default='', max_length=20, verbose_name='真实姓名'),
        ),
    ]
