# Generated by Django 2.0.5 on 2018-06-06 02:24

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_doctors_real_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='doctors',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='doctors',
            name='id_num',
            field=models.CharField(default='', max_length=18, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, default='upload/image/users/default.jpg', null=True, upload_to='upload/images/users/%Y/%m', verbose_name='用户头像'),
        ),
    ]
