# Generated by Django 2.0.5 on 2018-06-06 11:03

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180606_0224'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='doctors',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='is_doctor',
            field=models.BooleanField(default=False, verbose_name='是否是医生?'),
        ),
    ]
