# Generated by Django 2.0.5 on 2018-06-06 02:28

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_auto_20180606_0224'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0004_auto_20180606_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='病历标题')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2018, 6, 6, 2, 28, 38, 497285), verbose_name='病历创建时间')),
                ('desc', ckeditor.fields.RichTextField(verbose_name='病历内容')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Doctors', verbose_name='医生')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital', verbose_name='创建病历时所属医院')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='病人')),
            ],
            options={
                'verbose_name': '病历',
                'verbose_name_plural': '病历',
            },
        ),
    ]
