# Generated by Django 2.0.5 on 2018-06-06 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 2, 29, 17, 337066), verbose_name='病历创建时间'),
        ),
    ]
