# Generated by Django 2.0.5 on 2018-06-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='district',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='city',
        ),
        migrations.RemoveField(
            model_name='province',
            name='add_time',
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=20, verbose_name='行政区域'),
        ),
    ]
