# Generated by Django 2.0.5 on 2018-06-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20180605_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='level',
            field=models.SmallIntegerField(choices=[(0, '三级甲(特)医院'), (1, '三级医院'), (2, '二级医院'), (3, '一级医院')], default=0, verbose_name='医院等级'),
        ),
    ]
