# Generated by Django 2.0.5 on 2018-06-06 02:24

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_hospital_level'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hospital',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/images/hospital/%Y/%m', verbose_name='医院图片'),
        ),
    ]
